"""
EIDOS Dynamic Tool Builder — Genera herramientas al vuelo
Inspirado en IronClaw: describe lo que necesitas y EIDOS lo construye.

Las tools se generan, validan en sandbox, y registran automáticamente.
"""

import os
import re
import ast
import json
import time
import sqlite3
from core.db import get_conn
import hashlib
import subprocess
import textwrap
from pathlib import Path
from typing import Optional, Dict, List, Any, Tuple
from dataclasses import dataclass, field

# ─── Constantes ──────────────────────────────────────────────────────────────

EIDOS_DIR = Path.home() / ".eidos"
TOOLS_DIR = EIDOS_DIR / "dynamic_tools"
DB_PATH = EIDOS_DIR / "dynamic_tools.db"

TOOL_TEMPLATE = '''"""
{description}
Auto-generated by EIDOS Dynamic Tool Builder
Created: {created_at}
"""

import os
import sys
import json
import subprocess
from pathlib import Path
from core.db import get_conn


def {name}({params}):
    """
    {docstring}

    Args:
{args_doc}
    Returns:
        {returns}
    """
    try:
{body}
    except Exception as e:
        return {{"success": False, "error": str(e)}}


# ─── Metadata ────────────────────────────────────────────────────────────────
TOOL_META = {{
    "name": "{name}",
    "description": "{description}",
    "created_at": "{created_at}",
    "version": "1.0",
}}

if __name__ == "__main__":
    # Quick test
    print(f"Testing {name}...")
    result = {name}({test_args})
    print(f"Result: {{result}}")
'''

# ─── Dataclass ───────────────────────────────────────────────────────────────

@dataclass
class ToolResult:
    success: bool
    tool_name: str = ""
    tool_path: str = ""
    error: str = ""
    code: str = ""
    validation: Dict = field(default_factory=dict)


class DynamicToolBuilder:
    """
    Genera tools Python al vuelo basándose en descripciones.

    Features:
    - Genera código desde descripción natural
    - Valida sintaxis con AST
    - Prueba en sandbox antes de registrar
    - Auto-cleanup de tools con baja success rate
    - Integración con skill_registry
    """

    def __init__(self):
        TOOLS_DIR.mkdir(parents=True, exist_ok=True)
        self.db = get_conn(str(DB_PATH), check_same_thread=False)
        self.db.row_factory = sqlite3.Row
        self._init_db()

        # Patrones comunes para generación rápida (sin LLM)
        self._quick_patterns = {
            "file_reader": self._gen_file_reader,
            "file_writer": self._gen_file_writer,
            "http_get": self._gen_http_get,
            "json_parser": self._gen_json_parser,
            "csv_processor": self._gen_csv_processor,
            "regex_extractor": self._gen_regex_extractor,
            "system_check": self._gen_system_check,
            "port_scanner": self._gen_port_scanner,
            "hash_calculator": self._gen_hash_calculator,
            "text_transformer": self._gen_text_transformer,
        }

    def _init_db(self):
        self.db.executescript("""
            CREATE TABLE IF NOT EXISTS tools (
                name TEXT PRIMARY KEY,
                description TEXT,
                path TEXT,
                code_hash TEXT,
                created_at REAL,
                usage_count INTEGER DEFAULT 0,
                success_count INTEGER DEFAULT 0,
                fail_count INTEGER DEFAULT 0,
                active INTEGER DEFAULT 1,
                source TEXT DEFAULT 'generated'
            );
            CREATE TABLE IF NOT EXISTS tool_log (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                tool_name TEXT,
                action TEXT,
                details TEXT,
                timestamp REAL
            );
        """)
        self.db.commit()

    def _log(self, tool_name: str, action: str, details: str = ""):
        self.db.execute(
            "INSERT INTO tool_log (tool_name, action, details, timestamp) VALUES (?, ?, ?, ?)",
            (tool_name, action, details, time.time())
        )
        self.db.commit()

    # ─── Generación Quick (sin LLM) ─────────────────────────────────────

    def _gen_file_reader(self, params: Dict) -> str:
        return textwrap.dedent("""
        path = str(path)
        if not os.path.exists(path):
            return {"success": False, "error": f"File not found: {path}"}
        with open(path, 'r', encoding='utf-8', errors='ignore') as f:
            content = f.read()
        return {"success": True, "content": content, "size": len(content)}
        """).strip()

    def _gen_file_writer(self, params: Dict) -> str:
        return textwrap.dedent("""
        path = str(path)
        os.makedirs(os.path.dirname(path) or '.', exist_ok=True)
        with open(path, 'w', encoding='utf-8') as f:
            f.write(str(content))
        return {"success": True, "path": path, "bytes_written": len(str(content))}
        """).strip()

    def _gen_http_get(self, params: Dict) -> str:
        return textwrap.dedent("""
        import urllib.request
        req = urllib.request.Request(url, headers={'User-Agent': 'EIDOS/1.0'})
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            data = resp.read().decode('utf-8', errors='ignore')
        return {"success": True, "status": resp.status, "data": data[:10000]}
        """).strip()

    def _gen_json_parser(self, params: Dict) -> str:
        return textwrap.dedent("""
        if os.path.exists(str(data)):
            with open(str(data), 'r') as f:
                parsed = json.load(f)
        else:
            parsed = json.loads(str(data))
        if key:
            parts = key.split('.')
            result = parsed
            for p in parts:
                result = result[p] if isinstance(result, dict) else result[int(p)]
            return {"success": True, "value": result}
        return {"success": True, "data": parsed}
        """).strip()

    def _gen_csv_processor(self, params: Dict) -> str:
        return textwrap.dedent("""
        import csv
        rows = []
        with open(str(path), 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                rows.append(dict(row))
        return {"success": True, "rows": len(rows), "data": rows[:100], "columns": list(rows[0].keys()) if rows else []}
        """).strip()

    def _gen_regex_extractor(self, params: Dict) -> str:
        return textwrap.dedent("""
        import re as _re
        matches = _re.findall(pattern, text)
        return {"success": True, "matches": matches, "count": len(matches)}
        """).strip()

    def _gen_system_check(self, params: Dict) -> str:
        return textwrap.dedent("""
        import shutil
        info = {
            "cpu_count": os.cpu_count(),
            "cwd": os.getcwd(),
            "user": os.getenv("USER", "unknown"),
            "disk_free_gb": round(shutil.disk_usage("/").free / (1024**3), 2),
            "disk_total_gb": round(shutil.disk_usage("/").total / (1024**3), 2),
            "pid": os.getpid(),
        }
        # Memory
        try:
            with open("/proc/meminfo") as f:
                for line in f:
                    if "MemAvailable" in line:
                        info["mem_available_mb"] = int(line.split()[1]) // 1024
                    elif "MemTotal" in line:
                        info["mem_total_mb"] = int(line.split()[1]) // 1024
        except Exception:
            pass  # error no crítico, continuar
        return {"success": True, **info}
        """).strip()

    def _gen_port_scanner(self, params: Dict) -> str:
        return textwrap.dedent("""
        import socket
        open_ports = []
        for port in range(start_port, min(end_port + 1, start_port + 1000)):
            try:
                s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                s.settimeout(0.5)
                if s.connect_ex((host, port)) == 0:
                    open_ports.append(port)
                s.close()
            except Exception:
                pass  # error no crítico, continuar
        return {"success": True, "host": host, "open_ports": open_ports, "scanned": end_port - start_port + 1}
        """).strip()

    def _gen_hash_calculator(self, params: Dict) -> str:
        return textwrap.dedent("""
        import hashlib as _hl
        if os.path.exists(str(data)):
            with open(str(data), 'rb') as f:
                raw = f.read()
        else:
            raw = str(data).encode()
        return {
            "success": True,
            "md5": _hl.md5(raw).hexdigest(),
            "sha256": _hl.sha256(raw).hexdigest(),
            "size": len(raw)
        }
        """).strip()

    def _gen_text_transformer(self, params: Dict) -> str:
        return textwrap.dedent("""
        ops = {
            "upper": text.upper(),
            "lower": text.lower(),
            "title": text.title(),
            "reverse": text[::-1],
            "words": len(text.split()),
            "lines": len(text.splitlines()),
            "chars": len(text),
        }
        if operation in ops:
            return {"success": True, "result": ops[operation]}
        return {"success": True, "all": {k: str(v)[:200] for k, v in ops.items()}}
        """).strip()

    # ─── Validación ──────────────────────────────────────────────────────

    def _validate_syntax(self, code: str) -> Tuple[bool, str]:
        """Valida sintaxis Python con AST"""
        try:
            ast.parse(code)
            return True, "OK"
        except SyntaxError as e:
            return False, f"SyntaxError línea {e.lineno}: {e.msg}"

    def _validate_safety(self, code: str) -> Tuple[bool, List[str]]:
        """Verifica que el código no tenga operaciones peligrosas"""
        warnings = []
        dangerous = [
            (r'\bos\.system\b', "os.system() detectado — usar subprocess"),
            (r'\beval\s*\(', "eval() detectado — peligroso"),
            (r'\b__import__\b', "__import__ detectado"),
            (r'\brm\s+-rf\b', "rm -rf detectado"),
            (r'\bchmod\s+777\b', "chmod 777 detectado"),
            (r'\bformat\s+/', "format disk detectado"),
        ]
        for pattern, msg in dangerous:
            if re.search(pattern, code):
                warnings.append(msg)

        return len(warnings) == 0, warnings

    def _test_in_sandbox(self, tool_path: str, test_args: str = "") -> Tuple[bool, str]:
        """Prueba el tool en un subprocess limitado"""
        try:
            result = subprocess.run(
                ["python3", tool_path],
                capture_output=True, text=True, timeout=10,
                cwd=str(TOOLS_DIR)
            )
            if result.returncode == 0:
                return True, result.stdout[:500]
            else:
                return False, result.stderr[:500]
        except subprocess.TimeoutExpired:
            return False, "Timeout (10s)"
        except Exception as e:
            return False, str(e)

    # ─── API Principal ───────────────────────────────────────────────────

    def build_tool(self, description: str, name: str = None,
                   examples: List[Dict] = None) -> ToolResult:
        """
        Genera un tool a partir de una descripción.

        Args:
            description: Qué debe hacer el tool
            name: Nombre del tool (auto-generado si None)
            examples: Lista de {input: ..., output: ...}

        Returns:
            ToolResult con path al tool generado
        """
        print(f"🔧 [DynamicTools] Generando tool: {description[:60]}...")

        # Auto-nombre
        if not name:
            name = re.sub(r'[^a-z0-9_]', '_', description.lower()[:40]).strip('_')
            name = re.sub(r'_+', '_', name)

        # Buscar patrón quick match
        desc_lower = description.lower()
        quick_gen = None
        params_map = {}

        if any(w in desc_lower for w in ["read file", "leer archivo", "open file"]):
            quick_gen = "file_reader"
            params_map = {"params": "path", "args_doc": "        path: Ruta del archivo",
                          "returns": "dict con content", "test_args": '"test.txt"'}
        elif any(w in desc_lower for w in ["write file", "escribir", "save file"]):
            quick_gen = "file_writer"
            params_map = {"params": "path, content", "args_doc": "        path: Ruta\n        content: Contenido",
                          "returns": "dict con bytes_written", "test_args": '"/tmp/test.txt", "hello"'}
        elif any(w in desc_lower for w in ["http", "fetch", "download", "url"]):
            quick_gen = "http_get"
            params_map = {"params": "url, timeout=10", "args_doc": "        url: URL\n        timeout: Timeout en segundos",
                          "returns": "dict con data", "test_args": '"https://example.com"'}
        elif any(w in desc_lower for w in ["json", "parse json"]):
            quick_gen = "json_parser"
            params_map = {"params": "data, key=None", "args_doc": "        data: JSON string o path\n        key: Key dot-notation",
                          "returns": "dict con data/value", "test_args": '\'{"a":1}\''}
        elif any(w in desc_lower for w in ["csv"]):
            quick_gen = "csv_processor"
            params_map = {"params": "path", "args_doc": "        path: Ruta CSV",
                          "returns": "dict con rows", "test_args": '"test.csv"'}
        elif any(w in desc_lower for w in ["regex", "extract pattern", "match"]):
            quick_gen = "regex_extractor"
            params_map = {"params": "text, pattern", "args_doc": "        text: Texto\n        pattern: Regex",
                          "returns": "dict con matches", "test_args": '"hello 123 world 456", r"\\d+"'}
        elif any(w in desc_lower for w in ["system", "check system", "system info"]):
            quick_gen = "system_check"
            params_map = {"params": "", "args_doc": "        (sin argumentos)",
                          "returns": "dict con info del sistema", "test_args": ""}
        elif any(w in desc_lower for w in ["port", "scan port", "escanear puerto"]):
            quick_gen = "port_scanner"
            params_map = {"params": 'host="127.0.0.1", start_port=1, end_port=1024',
                          "args_doc": "        host: IP/hostname\n        start_port: Puerto inicio\n        end_port: Puerto fin",
                          "returns": "dict con open_ports", "test_args": '"127.0.0.1", 80, 85'}
        elif any(w in desc_lower for w in ["hash", "md5", "sha256", "checksum"]):
            quick_gen = "hash_calculator"
            params_map = {"params": "data", "args_doc": "        data: Texto o ruta de archivo",
                          "returns": "dict con md5, sha256", "test_args": '"hello world"'}
        elif any(w in desc_lower for w in ["text", "transform", "convert text"]):
            quick_gen = "text_transformer"
            params_map = {"params": 'text, operation="all"',
                          "args_doc": "        text: Texto\n        operation: upper/lower/title/reverse/words/lines/chars/all",
                          "returns": "dict con result", "test_args": '"Hello World", "upper"'}

        # Generar código
        if quick_gen and quick_gen in self._quick_patterns:
            body_raw = self._quick_patterns[quick_gen](params_map)
            body = textwrap.indent(body_raw, "        ")
            code = TOOL_TEMPLATE.format(
                description=description,
                name=name,
                params=params_map.get("params", ""),
                docstring=description,
                args_doc=params_map.get("args_doc", ""),
                returns=params_map.get("returns", "dict"),
                body=body,
                test_args=params_map.get("test_args", ""),
                created_at=time.strftime("%Y-%m-%d %H:%M:%S"),
            )
        else:
            # Generación genérica (plantilla simple)
            body = '        return {"success": True, "message": "Tool ejecutado", "args": locals()}'
            code = TOOL_TEMPLATE.format(
                description=description,
                name=name,
                params="**kwargs",
                docstring=description,
                args_doc="        **kwargs: Argumentos variables",
                returns="dict",
                body=body,
                test_args="",
                created_at=time.strftime("%Y-%m-%d %H:%M:%S"),
            )

        # Validar
        syntax_ok, syntax_msg = self._validate_syntax(code)
        if not syntax_ok:
            print(f"❌ [DynamicTools] Error de sintaxis: {syntax_msg}")
            return ToolResult(success=False, error=syntax_msg, code=code)

        safe, warnings = self._validate_safety(code)
        if not safe:
            print(f"⚠️  [DynamicTools] Warnings de seguridad: {warnings}")

        # Guardar
        tool_path = TOOLS_DIR / f"{name}.py"
        tool_path.write_text(code)

        # Test en sandbox
        test_ok, test_output = self._test_in_sandbox(str(tool_path))

        # Registrar en DB
        code_hash = hashlib.md5(code.encode()).hexdigest()
        self.db.execute("""
            INSERT OR REPLACE INTO tools (name, description, path, code_hash, created_at, active, source)
            VALUES (?, ?, ?, ?, ?, 1, 'generated')
        """, (name, description, str(tool_path), code_hash, time.time()))
        self.db.commit()

        self._log(name, "created", f"syntax={syntax_ok}, safe={safe}, test={test_ok}")
        status = "✅" if test_ok else "⚠️"
        print(f"{status} [DynamicTools] Tool '{name}' generado → {tool_path}")

        return ToolResult(
            success=True, tool_name=name, tool_path=str(tool_path),
            code=code, validation={"syntax": syntax_ok, "safe": safe,
                                    "warnings": warnings, "test_ok": test_ok,
                                    "test_output": test_output}
        )

    def from_error(self, error_msg: str, context: str = "") -> ToolResult:
        """Genera un tool que resuelve un tipo de error"""
        # Análisis del error
        if "ModuleNotFoundError" in error_msg:
            module = re.search(r"No module named '(\w+)'", error_msg)
            if module:
                mod_name = module.group(1)
                return self.build_tool(
                    f"Install and import {mod_name} module",
                    name=f"install_{mod_name}"
                )

        if "FileNotFoundError" in error_msg:
            return self.build_tool("Read file with error handling", name="safe_file_reader")

        if "ConnectionError" in error_msg or "timeout" in error_msg.lower():
            return self.build_tool("HTTP fetch with retry and timeout", name="resilient_fetch")

        # Genérico
        return self.build_tool(f"Handle error: {error_msg[:100]}", name="error_handler")

    def record_usage(self, tool_name: str, success: bool):
        """Registra uso de un tool"""
        if success:
            self.db.execute(
                "UPDATE tools SET usage_count = usage_count + 1, success_count = success_count + 1 WHERE name = ?",
                (tool_name,)
            )
        else:
            self.db.execute(
                "UPDATE tools SET usage_count = usage_count + 1, fail_count = fail_count + 1 WHERE name = ?",
                (tool_name,)
            )
        self.db.commit()

    def cleanup(self, min_usage: int = 5, min_success_rate: float = 0.5):
        """Desactiva tools con baja success rate"""
        tools = self.db.execute(
            "SELECT * FROM tools WHERE active = 1 AND usage_count >= ?",
            (min_usage,)
        ).fetchall()

        deactivated = []
        for t in tools:
            rate = t["success_count"] / max(t["usage_count"], 1)
            if rate < min_success_rate:
                self.db.execute(
                    "UPDATE tools SET active = 0 WHERE name = ?",
                    (t["name"],)
                )
                deactivated.append(t["name"])
                self._log(t["name"], "deactivated", f"success_rate={rate:.2f}")

        self.db.commit()
        if deactivated:
            print(f"🧹 [DynamicTools] Desactivados {len(deactivated)} tools: {deactivated}")
        return deactivated

    def list_tools(self, active_only: bool = True) -> List[Dict]:
        """Lista tools registrados"""
        query = "SELECT * FROM tools"
        if active_only:
            query += " WHERE active = 1"
        query += " ORDER BY usage_count DESC"
        return [dict(r) for r in self.db.execute(query).fetchall()]

    def get_tool(self, name: str) -> Optional[Dict]:
        """Obtiene info de un tool"""
        row = self.db.execute("SELECT * FROM tools WHERE name = ?", (name,)).fetchone()
        return dict(row) if row else None

    def get_stats(self) -> Dict:
        """Estadísticas generales"""
        total = self.db.execute("SELECT COUNT(*) FROM tools").fetchone()[0]
        active = self.db.execute("SELECT COUNT(*) FROM tools WHERE active = 1").fetchone()[0]
        total_usage = self.db.execute("SELECT SUM(usage_count) FROM tools").fetchone()[0] or 0
        return {
            "total_tools": total,
            "active_tools": active,
            "total_usage": total_usage,
            "tools_dir": str(TOOLS_DIR),
        }

    def __del__(self):
        try:
            self.db.close()
        except Exception:
            pass  # error no crítico, continuar
# ─── Test ────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("=== Test Dynamic Tool Builder ===\n")

    builder = DynamicToolBuilder()

    # Test 1: Generar tool de system check
    print("Test 1: System check tool")
    r = builder.build_tool("Check system information and resources")
    assert r.success
    print(f"  ✅ {r.tool_name} → {r.tool_path}\n")

    # Test 2: Hash calculator
    print("Test 2: Hash calculator tool")
    r = builder.build_tool("Calculate hash md5 and sha256 of data")
    assert r.success
    print(f"  ✅ {r.tool_name} → validation: {r.validation}\n")

    # Test 3: Port scanner
    print("Test 3: Port scanner tool")
    r = builder.build_tool("Scan open ports on a host")
    assert r.success
    print(f"  ✅ {r.tool_name}\n")

    # Test 4: From error
    print("Test 4: Generate from error")
    r = builder.from_error("ModuleNotFoundError: No module named 'pandas'")
    assert r.success
    print(f"  ✅ {r.tool_name}\n")

    # Test 5: List tools
    print("Test 5: List tools")
    tools = builder.list_tools()
    for t in tools:
        print(f"  📦 {t['name']} (uses: {t['usage_count']}, active: {t['active']})")

    # Stats
    print(f"\nStats: {builder.get_stats()}")

    print("\n✅ Dynamic Tool Builder funcional")
